//! Frozen vectors: 201 tables and the exact bytes they render to,
//! recorded once so the crate proves itself on every run with no generator and
//! no network.
//!
//! They cover 92 groups: shapes, hostile cells, alignment combinations, unicode
//! text, and randomised tables.

mod common;

use common::parse_tables;
use gfm_table::Alignment::{Center as C, Left as L, None as N, Right as R};
use gfm_table::{Alignment, Table};

struct Vector {
    id: &'static str,
    /// The width function the vector was recorded with: UTF-16 code units when
    /// true, `char` values when false.
    utf16: bool,
    alignments: &'static [Alignment],
    rows: &'static [&'static [&'static str]],
    expected: &'static str,
}

fn render(vector: &Vector) -> String {
    let mut table = Table::new();
    for row in vector.rows {
        table.push_row(*row);
    }
    table.set_alignments(vector.alignments.to_vec());
    if vector.utf16 {
        return table
            .with_cell_width(|cell| cell.encode_utf16().count())
            .render();
    }
    table.render()
}

#[test]
fn every_frozen_vector_renders_to_its_recorded_bytes() {
    for vector in VECTORS {
        assert_eq!(render(vector), vector.expected, "vector {}", vector.id);
    }
    assert_eq!(VECTORS.len(), 201);
}

#[test]
fn every_frozen_vector_parses_as_one_table() {
    for vector in VECTORS {
        let out = render(vector);
        let parsed = parse_tables(&out);
        assert_eq!(parsed.len(), 1, "vector {}", vector.id);
        assert_eq!(
            parsed[0].rows.len(),
            vector.rows.len(),
            "vector {}",
            vector.id
        );
    }
}

const VECTORS: &[Vector] = &[
    Vector {
        id: "align.combo/1294",
        utf16: true,
        alignments: &[C],
        rows: &[&["H0"], &["longer-cell-0"], &["x"]],
        expected: "|       H0      |\n| :-----------: |\n| longer-cell-0 |\n|       x       |",
    },
    Vector {
        id: "align.combo/1315",
        utf16: true,
        alignments: &[L, R],
        rows: &[&["H0", "H1"], &["longer-cell-0", "longer-cell-1"], &["x", "x"]],
        expected: "| H0            |            H1 |\n| :------------ | ------------: |\n| longer-cell-0 | longer-cell-1 |\n| x             |             x |",
    },
    Vector {
        id: "align.combo/1336",
        utf16: true,
        alignments: &[C, L],
        rows: &[&["H0", "H1"], &["longer-cell-0", "longer-cell-1"], &["x", "x"]],
        expected: "|       H0      | H1            |\n| :-----------: | :------------ |\n| longer-cell-0 | longer-cell-1 |\n|       x       | x             |",
    },
    Vector {
        id: "align.combo/1357",
        utf16: true,
        alignments: &[N, L, N],
        rows: &[&["H0", "H1", "H2"], &["longer-cell-0", "longer-cell-1", "longer-cell-2"], &["x", "x", "x"]],
        expected: "| H0            | H1            | H2            |\n| ------------- | :------------ | ------------- |\n| longer-cell-0 | longer-cell-1 | longer-cell-2 |\n| x             | x             | x             |",
    },
    Vector {
        id: "align.combo/1378",
        utf16: true,
        alignments: &[N, R, C],
        rows: &[&["H0", "H1", "H2"], &["longer-cell-0", "longer-cell-1", "longer-cell-2"], &["x", "x", "x"]],
        expected: "| H0            |            H1 |       H2      |\n| ------------- | ------------: | :-----------: |\n| longer-cell-0 | longer-cell-1 | longer-cell-2 |\n| x             |             x |       x       |",
    },
    Vector {
        id: "align.combo/1399",
        utf16: true,
        alignments: &[L, N, R],
        rows: &[&["H0", "H1", "H2"], &["longer-cell-0", "longer-cell-1", "longer-cell-2"], &["x", "x", "x"]],
        expected: "| H0            | H1            |            H2 |\n| :------------ | ------------- | ------------: |\n| longer-cell-0 | longer-cell-1 | longer-cell-2 |\n| x             | x             |             x |",
    },
    Vector {
        id: "align.combo/1420",
        utf16: true,
        alignments: &[L, R, L],
        rows: &[&["H0", "H1", "H2"], &["longer-cell-0", "longer-cell-1", "longer-cell-2"], &["x", "x", "x"]],
        expected: "| H0            |            H1 | H2            |\n| :------------ | ------------: | :------------ |\n| longer-cell-0 | longer-cell-1 | longer-cell-2 |\n| x             |             x | x             |",
    },
    Vector {
        id: "align.combo/1441",
        utf16: true,
        alignments: &[R, N, N],
        rows: &[&["H0", "H1", "H2"], &["longer-cell-0", "longer-cell-1", "longer-cell-2"], &["x", "x", "x"]],
        expected: "|            H0 | H1            | H2            |\n| ------------: | ------------- | ------------- |\n| longer-cell-0 | longer-cell-1 | longer-cell-2 |\n|             x | x             | x             |",
    },
    Vector {
        id: "align.combo/1462",
        utf16: true,
        alignments: &[R, L, C],
        rows: &[&["H0", "H1", "H2"], &["longer-cell-0", "longer-cell-1", "longer-cell-2"], &["x", "x", "x"]],
        expected: "|            H0 | H1            |       H2      |\n| ------------: | :------------ | :-----------: |\n| longer-cell-0 | longer-cell-1 | longer-cell-2 |\n|             x | x             |       x       |",
    },
    Vector {
        id: "align.combo/1483",
        utf16: true,
        alignments: &[R, C, R],
        rows: &[&["H0", "H1", "H2"], &["longer-cell-0", "longer-cell-1", "longer-cell-2"], &["x", "x", "x"]],
        expected: "|            H0 |       H1      |            H2 |\n| ------------: | :-----------: | ------------: |\n| longer-cell-0 | longer-cell-1 | longer-cell-2 |\n|             x |       x       |             x |",
    },
    Vector {
        id: "align.combo/1504",
        utf16: true,
        alignments: &[C, L, L],
        rows: &[&["H0", "H1", "H2"], &["longer-cell-0", "longer-cell-1", "longer-cell-2"], &["x", "x", "x"]],
        expected: "|       H0      | H1            | H2            |\n| :-----------: | :------------ | :------------ |\n| longer-cell-0 | longer-cell-1 | longer-cell-2 |\n|       x       | x             | x             |",
    },
    Vector {
        id: "align.combo/1525",
        utf16: true,
        alignments: &[C, C, N],
        rows: &[&["H0", "H1", "H2"], &["longer-cell-0", "longer-cell-1", "longer-cell-2"], &["x", "x", "x"]],
        expected: "|       H0      |       H1      | H2            |\n| :-----------: | :-----------: | ------------- |\n| longer-cell-0 | longer-cell-1 | longer-cell-2 |\n|       x       |       x       | x             |",
    },
    Vector {
        id: "align.mismatch/1542",
        utf16: true,
        alignments: &[L],
        rows: &[&["a", "bb", "ccc"], &["dddd", "e", "ff"]],
        expected: "| a    | bb | ccc |\n| :--- | -- | --- |\n| dddd | e  | ff  |",
    },
    Vector {
        id: "align.mismatch/1555",
        utf16: true,
        alignments: &[L, R, C],
        rows: &[&["a"]],
        expected: "| a  |\n| :- |",
    },
    Vector {
        id: "align.mismatch/1565",
        utf16: true,
        alignments: &[L, R, C, L, R, C, L, R],
        rows: &[&["a"]],
        expected: "| a  |\n| :- |",
    },
    Vector {
        id: "align.mismatch/1577",
        utf16: true,
        alignments: &[N, N, N],
        rows: &[&["a", "bb", "ccc"], &["dddd", "e", "ff"]],
        expected: "| a    | bb | ccc |\n| ---- | -- | --- |\n| dddd | e  | ff  |",
    },
    Vector {
        id: "align.mismatch/1590",
        utf16: true,
        alignments: &[L, R, C],
        rows: &[&["a"]],
        expected: "| a  |\n| :- |",
    },
    Vector {
        id: "align.mismatch/1600",
        utf16: true,
        alignments: &[N, N, N],
        rows: &[&["a"]],
        expected: "| a |\n| - |",
    },
    Vector {
        id: "align.mismatch/1612",
        utf16: true,
        alignments: &[N, N, N],
        rows: &[&["a", "bb", "ccc"], &["dddd", "e", "ff"]],
        expected: "| a    | bb | ccc |\n| ---- | -- | --- |\n| dddd | e  | ff  |",
    },
    Vector {
        id: "align.mismatch/1625",
        utf16: true,
        alignments: &[L],
        rows: &[&["a"]],
        expected: "| a  |\n| :- |",
    },
    Vector {
        id: "align.mismatch/1635",
        utf16: true,
        alignments: &[C],
        rows: &[&["a"]],
        expected: "|  a  |\n| :-: |",
    },
    Vector {
        id: "align.mismatch/1647",
        utf16: true,
        alignments: &[L, L, L],
        rows: &[&["a", "bb", "ccc"], &["dddd", "e", "ff"]],
        expected: "| a    | bb | ccc |\n| :--- | :- | :-- |\n| dddd | e  | ff  |",
    },
    Vector {
        id: "align.mismatch/1660",
        utf16: true,
        alignments: &[N],
        rows: &[&["a"]],
        expected: "| a |\n| - |",
    },
    Vector {
        id: "align.mismatch/1670",
        utf16: true,
        alignments: &[],
        rows: &[&["a"]],
        expected: "| a |\n| - |",
    },
    Vector {
        id: "hostile.ampersand/1070",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "&amp;"]],
        expected: "| h | &amp; |\n| - | ----- |",
    },
    Vector {
        id: "hostile.ampersand/1080",
        utf16: true,
        alignments: &[],
        rows: &[&["&amp;", "&amp;"], &["&amp;", "&amp;"]],
        expected: "| &amp; | &amp; |\n| ----- | ----- |\n| &amp; | &amp; |",
    },
    Vector {
        id: "hostile.backslash-double/570",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "\\\\"]],
        expected: "| h | \\\\ |\n| - | -- |",
    },
    Vector {
        id: "hostile.backslash-double/580",
        utf16: true,
        alignments: &[],
        rows: &[&["\\\\", "\\\\"], &["\\\\", "\\\\"]],
        expected: "| \\\\ | \\\\ |\n| -- | -- |\n| \\\\ | \\\\ |",
    },
    Vector {
        id: "hostile.backslash-trailing/590",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "a\\"]],
        expected: "| h | a\\ |\n| - | -- |",
    },
    Vector {
        id: "hostile.backslash-trailing/600",
        utf16: true,
        alignments: &[],
        rows: &[&["a\\", "a\\"], &["a\\", "a\\"]],
        expected: "| a\\ | a\\ |\n| -- | -- |\n| a\\ | a\\ |",
    },
    Vector {
        id: "hostile.backslash/550",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "\\"]],
        expected: "| h | \\ |\n| - | - |",
    },
    Vector {
        id: "hostile.backslash/560",
        utf16: true,
        alignments: &[],
        rows: &[&["\\", "\\"], &["\\", "\\"]],
        expected: "| \\ | \\ |\n| - | - |\n| \\ | \\ |",
    },
    Vector {
        id: "hostile.backtick-span/630",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "`code`"]],
        expected: "| h | `code` |\n| - | ------ |",
    },
    Vector {
        id: "hostile.backtick-span/640",
        utf16: true,
        alignments: &[],
        rows: &[&["`code`", "`code`"], &["`code`", "`code`"]],
        expected: "| `code` | `code` |\n| ------ | ------ |\n| `code` | `code` |",
    },
    Vector {
        id: "hostile.backtick/610",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "`"]],
        expected: "| h | ` |\n| - | - |",
    },
    Vector {
        id: "hostile.backtick/620",
        utf16: true,
        alignments: &[],
        rows: &[&["`", "`"], &["`", "`"]],
        expected: "| ` | ` |\n| - | - |\n| ` | ` |",
    },
    Vector {
        id: "hostile.bell-etc/890",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "\u{1}\u{2}\u{7}"]],
        expected: "| h | \u{1}\u{2}\u{7} |\n| - | --- |",
    },
    Vector {
        id: "hostile.bell-etc/900",
        utf16: true,
        alignments: &[],
        rows: &[&["\u{1}\u{2}\u{7}", "\u{1}\u{2}\u{7}"], &["\u{1}\u{2}\u{7}", "\u{1}\u{2}\u{7}"]],
        expected: "| \u{1}\u{2}\u{7} | \u{1}\u{2}\u{7} |\n| --- | --- |\n| \u{1}\u{2}\u{7} | \u{1}\u{2}\u{7} |",
    },
    Vector {
        id: "hostile.colon-dash/1000",
        utf16: true,
        alignments: &[],
        rows: &[&[":---:", ":---:"], &[":---:", ":---:"]],
        expected: "| :---: | :---: |\n| ----- | ----- |\n| :---: | :---: |",
    },
    Vector {
        id: "hostile.colon-dash/990",
        utf16: true,
        alignments: &[],
        rows: &[&["h", ":---:"]],
        expected: "| h | :---: |\n| - | ----- |",
    },
    Vector {
        id: "hostile.dash-run/970",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "---"]],
        expected: "| h | --- |\n| - | --- |",
    },
    Vector {
        id: "hostile.dash-run/980",
        utf16: true,
        alignments: &[],
        rows: &[&["---", "---"], &["---", "---"]],
        expected: "| --- | --- |\n| --- | --- |\n| --- | --- |",
    },
    Vector {
        id: "hostile.form-feed/830",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "a\u{c}b"]],
        expected: "| h | a\u{c}b |\n| - | --- |",
    },
    Vector {
        id: "hostile.form-feed/840",
        utf16: true,
        alignments: &[],
        rows: &[&["a\u{c}b", "a\u{c}b"], &["a\u{c}b", "a\u{c}b"]],
        expected: "| a\u{c}b | a\u{c}b |\n| --- | --- |\n| a\u{c}b | a\u{c}b |",
    },
    Vector {
        id: "hostile.html-comment/1050",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "<!-- x -->"]],
        expected: "| h | <!-- x --> |\n| - | ---------- |",
    },
    Vector {
        id: "hostile.html-comment/1060",
        utf16: true,
        alignments: &[],
        rows: &[&["<!-- x -->", "<!-- x -->"], &["<!-- x -->", "<!-- x -->"]],
        expected: "| <!-- x --> | <!-- x --> |\n| ---------- | ---------- |\n| <!-- x --> | <!-- x --> |",
    },
    Vector {
        id: "hostile.html-tag/1030",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "<b>x</b>"]],
        expected: "| h | <b>x</b> |\n| - | -------- |",
    },
    Vector {
        id: "hostile.html-tag/1040",
        utf16: true,
        alignments: &[],
        rows: &[&["<b>x</b>", "<b>x</b>"], &["<b>x</b>", "<b>x</b>"]],
        expected: "| <b>x</b> | <b>x</b> |\n| -------- | -------- |\n| <b>x</b> | <b>x</b> |",
    },
    Vector {
        id: "hostile.line-separator/910",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "a\u{2028}b"]],
        expected: "| h | a\u{2028}b |\n| - | --- |",
    },
    Vector {
        id: "hostile.line-separator/920",
        utf16: true,
        alignments: &[],
        rows: &[&["a\u{2028}b", "a\u{2028}b"], &["a\u{2028}b", "a\u{2028}b"]],
        expected: "| a\u{2028}b | a\u{2028}b |\n| --- | --- |\n| a\u{2028}b | a\u{2028}b |",
    },
    Vector {
        id: "hostile.markdown-blockquote/1190",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "> quote"]],
        expected: "| h | > quote |\n| - | ------- |",
    },
    Vector {
        id: "hostile.markdown-blockquote/1200",
        utf16: true,
        alignments: &[],
        rows: &[&["> quote", "> quote"], &["> quote", "> quote"]],
        expected: "| > quote | > quote |\n| ------- | ------- |\n| > quote | > quote |",
    },
    Vector {
        id: "hostile.markdown-bold/1130",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "**bold**"]],
        expected: "| h | **bold** |\n| - | -------- |",
    },
    Vector {
        id: "hostile.markdown-bold/1140",
        utf16: true,
        alignments: &[],
        rows: &[&["**bold**", "**bold**"], &["**bold**", "**bold**"]],
        expected: "| **bold** | **bold** |\n| -------- | -------- |\n| **bold** | **bold** |",
    },
    Vector {
        id: "hostile.markdown-bullet/1110",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "- item"]],
        expected: "| h | - item |\n| - | ------ |",
    },
    Vector {
        id: "hostile.markdown-bullet/1120",
        utf16: true,
        alignments: &[],
        rows: &[&["- item", "- item"], &["- item", "- item"]],
        expected: "| - item | - item |\n| ------ | ------ |\n| - item | - item |",
    },
    Vector {
        id: "hostile.markdown-fence/1250",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "```js"]],
        expected: "| h | ```js |\n| - | ----- |",
    },
    Vector {
        id: "hostile.markdown-fence/1260",
        utf16: true,
        alignments: &[],
        rows: &[&["```js", "```js"], &["```js", "```js"]],
        expected: "| ```js | ```js |\n| ----- | ----- |\n| ```js | ```js |",
    },
    Vector {
        id: "hostile.markdown-heading/1090",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "# heading"]],
        expected: "| h | # heading |\n| - | --------- |",
    },
    Vector {
        id: "hostile.markdown-heading/1100",
        utf16: true,
        alignments: &[],
        rows: &[&["# heading", "# heading"], &["# heading", "# heading"]],
        expected: "| # heading | # heading |\n| --------- | --------- |\n| # heading | # heading |",
    },
    Vector {
        id: "hostile.markdown-hr/1210",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "***"]],
        expected: "| h | *** |\n| - | --- |",
    },
    Vector {
        id: "hostile.markdown-hr/1220",
        utf16: true,
        alignments: &[],
        rows: &[&["***", "***"], &["***", "***"]],
        expected: "| *** | *** |\n| --- | --- |\n| *** | *** |",
    },
    Vector {
        id: "hostile.markdown-image/1170",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "![a](b)"]],
        expected: "| h | ![a](b) |\n| - | ------- |",
    },
    Vector {
        id: "hostile.markdown-image/1180",
        utf16: true,
        alignments: &[],
        rows: &[&["![a](b)", "![a](b)"], &["![a](b)", "![a](b)"]],
        expected: "| ![a](b) | ![a](b) |\n| ------- | ------- |\n| ![a](b) | ![a](b) |",
    },
    Vector {
        id: "hostile.markdown-link/1150",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "[a](b)"]],
        expected: "| h | [a](b) |\n| - | ------ |",
    },
    Vector {
        id: "hostile.markdown-link/1160",
        utf16: true,
        alignments: &[],
        rows: &[&["[a](b)", "[a](b)"], &["[a](b)", "[a](b)"]],
        expected: "| [a](b) | [a](b) |\n| ------ | ------ |\n| [a](b) | [a](b) |",
    },
    Vector {
        id: "hostile.nbsp/950",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "a\u{a0}b"]],
        expected: "| h | a\u{a0}b |\n| - | --- |",
    },
    Vector {
        id: "hostile.nbsp/960",
        utf16: true,
        alignments: &[],
        rows: &[&["a\u{a0}b", "a\u{a0}b"], &["a\u{a0}b", "a\u{a0}b"]],
        expected: "| a\u{a0}b | a\u{a0}b |\n| --- | --- |\n| a\u{a0}b | a\u{a0}b |",
    },
    Vector {
        id: "hostile.nul/870",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "a\u{0}b"]],
        expected: "| h | a\u{0}b |\n| - | --- |",
    },
    Vector {
        id: "hostile.nul/880",
        utf16: true,
        alignments: &[],
        rows: &[&["a\u{0}b", "a\u{0}b"], &["a\u{0}b", "a\u{0}b"]],
        expected: "| a\u{0}b | a\u{0}b |\n| --- | --- |\n| a\u{0}b | a\u{0}b |",
    },
    Vector {
        id: "hostile.only-dashes/1010",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "-"]],
        expected: "| h | - |\n| - | - |",
    },
    Vector {
        id: "hostile.only-dashes/1020",
        utf16: true,
        alignments: &[],
        rows: &[&["-", "-"], &["-", "-"]],
        expected: "| - | - |\n| - | - |\n| - | - |",
    },
    Vector {
        id: "hostile.paragraph-separator/930",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "a\u{2029}b"]],
        expected: "| h | a\u{2029}b |\n| - | --- |",
    },
    Vector {
        id: "hostile.paragraph-separator/940",
        utf16: true,
        alignments: &[],
        rows: &[&["a\u{2029}b", "a\u{2029}b"], &["a\u{2029}b", "a\u{2029}b"]],
        expected: "| a\u{2029}b | a\u{2029}b |\n| --- | --- |\n| a\u{2029}b | a\u{2029}b |",
    },
    Vector {
        id: "hostile.pipe-escaped/530",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "a\\|b"]],
        expected: "| h | a\\|b |\n| - | ---- |",
    },
    Vector {
        id: "hostile.pipe-escaped/540",
        utf16: true,
        alignments: &[],
        rows: &[&["a\\|b", "a\\|b"], &["a\\|b", "a\\|b"]],
        expected: "| a\\|b | a\\|b |\n| ---- | ---- |\n| a\\|b | a\\|b |",
    },
    Vector {
        id: "hostile.setext-underline/1270",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "======"]],
        expected: "| h | ====== |\n| - | ------ |",
    },
    Vector {
        id: "hostile.setext-underline/1280",
        utf16: true,
        alignments: &[],
        rows: &[&["======", "======"], &["======", "======"]],
        expected: "| ====== | ====== |\n| ------ | ------ |\n| ====== | ====== |",
    },
    Vector {
        id: "hostile.tab-mid/810",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "a\tb"]],
        expected: "| h | a\tb |\n| - | --- |",
    },
    Vector {
        id: "hostile.tab-mid/820",
        utf16: true,
        alignments: &[],
        rows: &[&["a\tb", "a\tb"], &["a\tb", "a\tb"]],
        expected: "| a\tb | a\tb |\n| --- | --- |\n| a\tb | a\tb |",
    },
    Vector {
        id: "hostile.tab/790",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "\t"]],
        expected: "| h | \t |\n| - | - |",
    },
    Vector {
        id: "hostile.tab/800",
        utf16: true,
        alignments: &[],
        rows: &[&["\t", "\t"], &["\t", "\t"]],
        expected: "| \t | \t |\n| - | - |\n| \t | \t |",
    },
    Vector {
        id: "hostile.vertical-tab/850",
        utf16: true,
        alignments: &[],
        rows: &[&["h", "a\u{b}b"]],
        expected: "| h | a\u{b}b |\n| - | --- |",
    },
    Vector {
        id: "hostile.vertical-tab/860",
        utf16: true,
        alignments: &[],
        rows: &[&["a\u{b}b", "a\u{b}b"], &["a\u{b}b", "a\u{b}b"]],
        expected: "| a\u{b}b | a\u{b}b |\n| --- | --- |\n| a\u{b}b | a\u{b}b |",
    },
    Vector {
        id: "random/4358",
        utf16: true,
        alignments: &[C],
        rows: &[&[""], &["\u{645}&c#"]],
        expected: "|      |\n| :--: |\n| \u{645}&c# |",
    },
    Vector {
        id: "random/5647",
        utf16: true,
        alignments: &[],
        rows: &[&["*", "", "\u{200b}&Z\u{1f468}\u{200d}\u{1f469}\u{200d}\u{1f467}\u{200d}\u{1f466}\u{645}9e\u{301}"]],
        expected: "| * |   | \u{200b}&Z\u{1f468}\u{200d}\u{1f469}\u{200d}\u{1f467}\u{200d}\u{1f466}\u{645}9e\u{301} |\n| - | - | ------------------ |",
    },
    Vector {
        id: "scale.cols-1/3553",
        utf16: true,
        alignments: &[],
        rows: &[&["c0"], &["0"], &["0"]],
        expected: "| c0 |\n| -- |\n| 0  |\n| 0  |",
    },
    Vector {
        id: "scale.cols-1/3554",
        utf16: true,
        alignments: &[N],
        rows: &[&["c0"], &["0"]],
        expected: "| c0 |\n| -- |\n| 0  |",
    },
    Vector {
        id: "scale.cols-2/3555",
        utf16: true,
        alignments: &[],
        rows: &[&["c0", "c1"], &["0", "1"], &["0", "1"]],
        expected: "| c0 | c1 |\n| -- | -- |\n| 0  | 1  |\n| 0  | 1  |",
    },
    Vector {
        id: "scale.cols-2/3556",
        utf16: true,
        alignments: &[N, L],
        rows: &[&["c0", "c1"], &["0", "1"]],
        expected: "| c0 | c1 |\n| -- | :- |\n| 0  | 1  |",
    },
    Vector {
        id: "scale.cols-3/3557",
        utf16: true,
        alignments: &[],
        rows: &[&["c0", "c1", "c2"], &["0", "1", "4"], &["0", "1", "4"]],
        expected: "| c0 | c1 | c2 |\n| -- | -- | -- |\n| 0  | 1  | 4  |\n| 0  | 1  | 4  |",
    },
    Vector {
        id: "scale.cols-3/3558",
        utf16: true,
        alignments: &[N, L, R],
        rows: &[&["c0", "c1", "c2"], &["0", "1", "4"]],
        expected: "| c0 | c1 | c2 |\n| -- | :- | -: |\n| 0  | 1  |  4 |",
    },
    Vector {
        id: "scale.rows-1/3569",
        utf16: true,
        alignments: &[],
        rows: &[&["idx", "value"], &["0", ""]],
        expected: "| idx | value |\n| --- | ----- |\n| 0   |       |",
    },
    Vector {
        id: "scale.rows-2/3570",
        utf16: true,
        alignments: &[],
        rows: &[&["idx", "value"], &["0", ""], &["1", "v"]],
        expected: "| idx | value |\n| --- | ----- |\n| 0   |       |\n| 1   | v     |",
    },
    Vector {
        id: "scale.rows-3/3571",
        utf16: true,
        alignments: &[],
        rows: &[&["idx", "value"], &["0", ""], &["1", "v"], &["2", "vv"]],
        expected: "| idx | value |\n| --- | ----- |\n| 0   |       |\n| 1   | v     |\n| 2   | vv    |",
    },
    Vector {
        id: "shape.all-empty-cells/217",
        utf16: false,
        alignments: &[],
        rows: &[&["", ""], &["", ""]],
        expected: "|   |   |\n| - | - |\n|   |   |",
    },
    Vector {
        id: "shape.all-empty-cells/222",
        utf16: true,
        alignments: &[C, C],
        rows: &[&["", ""], &["", ""]],
        expected: "|     |     |\n| :-: | :-: |\n|     |     |",
    },
    Vector {
        id: "shape.empty-header-with-body/142",
        utf16: false,
        alignments: &[],
        rows: &[&[], &["a", "b"]],
        expected: "|   |   |\n| - | - |\n| a | b |",
    },
    Vector {
        id: "shape.empty-header-with-body/147",
        utf16: true,
        alignments: &[C, C],
        rows: &[&[], &["a", "b"]],
        expected: "|     |     |\n| :-: | :-: |\n|  a  |  b  |",
    },
    Vector {
        id: "shape.header-only-1col/67",
        utf16: false,
        alignments: &[],
        rows: &[&["Alpha"]],
        expected: "| Alpha |\n| ----- |",
    },
    Vector {
        id: "shape.header-only-1col/72",
        utf16: true,
        alignments: &[C],
        rows: &[&["Alpha"]],
        expected: "| Alpha |\n| :---: |",
    },
    Vector {
        id: "shape.header-only/42",
        utf16: false,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"]],
        expected: "| Alpha | Bravo |\n| ----- | ----- |",
    },
    Vector {
        id: "shape.header-only/47",
        utf16: true,
        alignments: &[C, C],
        rows: &[&["Alpha", "Bravo"]],
        expected: "| Alpha | Bravo |\n| :---: | :---: |",
    },
    Vector {
        id: "shape.leading-trailing-space/417",
        utf16: false,
        alignments: &[],
        rows: &[&[" a ", "b "], &[" c", "d "]],
        expected: "|  a  | b  |\n| --- | -- |\n|  c  | d  |",
    },
    Vector {
        id: "shape.leading-trailing-space/422",
        utf16: true,
        alignments: &[C, C],
        rows: &[&[" a ", "b "], &[" c", "d "]],
        expected: "|  a  |  b  |\n| :-: | :-: |\n|   c |  d  |",
    },
    Vector {
        id: "shape.one-row-one-col/92",
        utf16: false,
        alignments: &[],
        rows: &[&["x"]],
        expected: "| x |\n| - |",
    },
    Vector {
        id: "shape.one-row-one-col/97",
        utf16: true,
        alignments: &[C],
        rows: &[&["x"]],
        expected: "|  x  |\n| :-: |",
    },
    Vector {
        id: "shape.ragged-empty-row-middle/367",
        utf16: false,
        alignments: &[],
        rows: &[&["a", "b"], &[], &["c", "d"]],
        expected: "| a | b |\n| - | - |\n|   |   |\n| c | d |",
    },
    Vector {
        id: "shape.ragged-empty-row-middle/372",
        utf16: true,
        alignments: &[C, C],
        rows: &[&["a", "b"], &[], &["c", "d"]],
        expected: "|  a  |  b  |\n| :-: | :-: |\n|     |     |\n|  c  |  d  |",
    },
    Vector {
        id: "shape.ragged-long-body/292",
        utf16: false,
        alignments: &[],
        rows: &[&["a"], &["b", "c", "d"], &["e", "f"]],
        expected: "| a |   |   |\n| - | - | - |\n| b | c | d |\n| e | f |   |",
    },
    Vector {
        id: "shape.ragged-long-body/297",
        utf16: true,
        alignments: &[C, C, C],
        rows: &[&["a"], &["b", "c", "d"], &["e", "f"]],
        expected: "|  a  |     |     |\n| :-: | :-: | :-: |\n|  b  |  c  |  d  |\n|  e  |  f  |     |",
    },
    Vector {
        id: "shape.ragged-narrowing/342",
        utf16: false,
        alignments: &[],
        rows: &[&["a", "a", "a", "a"], &["b", "b", "b"], &["c", "c"], &["d"]],
        expected: "| a | a | a | a |\n| - | - | - | - |\n| b | b | b |   |\n| c | c |   |   |\n| d |   |   |   |",
    },
    Vector {
        id: "shape.ragged-narrowing/347",
        utf16: true,
        alignments: &[C, C, C, C],
        rows: &[&["a", "a", "a", "a"], &["b", "b", "b"], &["c", "c"], &["d"]],
        expected: "|  a  |  a  |  a  |  a  |\n| :-: | :-: | :-: | :-: |\n|  b  |  b  |  b  |     |\n|  c  |  c  |     |     |\n|  d  |     |     |     |",
    },
    Vector {
        id: "shape.ragged-short-body/267",
        utf16: false,
        alignments: &[],
        rows: &[&["a", "b", "c"], &["d"]],
        expected: "| a | b | c |\n| - | - | - |\n| d |   |   |",
    },
    Vector {
        id: "shape.ragged-short-body/272",
        utf16: true,
        alignments: &[C, C, C],
        rows: &[&["a", "b", "c"], &["d"]],
        expected: "|  a  |  b  |  c  |\n| :-: | :-: | :-: |\n|  d  |     |     |",
    },
    Vector {
        id: "shape.ragged-widening/317",
        utf16: false,
        alignments: &[],
        rows: &[&["a"], &["b", "b"], &["c", "c", "c"], &["d", "d", "d", "d"]],
        expected: "| a |   |   |   |\n| - | - | - | - |\n| b | b |   |   |\n| c | c | c |   |\n| d | d | d | d |",
    },
    Vector {
        id: "shape.ragged-widening/322",
        utf16: true,
        alignments: &[C, C, C, C],
        rows: &[&["a"], &["b", "b"], &["c", "c", "c"], &["d", "d", "d", "d"]],
        expected: "|  a  |     |     |     |\n| :-: | :-: | :-: | :-: |\n|  b  |  b  |     |     |\n|  c  |  c  |  c  |     |\n|  d  |  d  |  d  |  d  |",
    },
    Vector {
        id: "shape.single-empty-cell/192",
        utf16: false,
        alignments: &[],
        rows: &[&[""]],
        expected: "|   |\n| - |",
    },
    Vector {
        id: "shape.single-empty-cell/197",
        utf16: true,
        alignments: &[C],
        rows: &[&[""]],
        expected: "|     |\n| :-: |",
    },
    Vector {
        id: "shape.square/242",
        utf16: false,
        alignments: &[],
        rows: &[&["a", "b"], &["c", "d"]],
        expected: "| a | b |\n| - | - |\n| c | d |",
    },
    Vector {
        id: "shape.square/247",
        utf16: true,
        alignments: &[C, C],
        rows: &[&["a", "b"], &["c", "d"]],
        expected: "|  a  |  b  |\n| :-: | :-: |\n|  c  |  d  |",
    },
    Vector {
        id: "shape.whitespace-only-cells/392",
        utf16: false,
        alignments: &[],
        rows: &[&[" ", "  "], &["\t", "   "]],
        expected: "|   |     |\n| - | --- |\n| \t |     |",
    },
    Vector {
        id: "shape.whitespace-only-cells/397",
        utf16: true,
        alignments: &[C, C],
        rows: &[&[" ", "  "], &["\t", "   "]],
        expected: "|     |     |\n| :-: | :-: |\n|  \t  |     |",
    },
    Vector {
        id: "unicode.accented-decomposed/3177",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["e\u{301}u\u{308}n\u{303}", "Charlie"], &["Delta", "e\u{301}u\u{308}n\u{303}"]],
        expected: "| Alpha  | Bravo   |\n| ------ | ------- |\n| e\u{301}u\u{308}n\u{303} | Charlie |\n| Delta  | e\u{301}u\u{308}n\u{303}  |",
    },
    Vector {
        id: "unicode.accented-decomposed/3201",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "e\u{301}u\u{308}n\u{303}e\u{301}u\u{308}n\u{303}e\u{301}u\u{308}n\u{303}"]],
        expected: "| ascii | e\u{301}u\u{308}n\u{303}e\u{301}u\u{308}n\u{303}e\u{301}u\u{308}n\u{303} |\n| ----- | ------------------ |",
    },
    Vector {
        id: "unicode.accented-precomposed/3129",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{e9}\u{fc}\u{f1}", "Charlie"], &["Delta", "\u{e9}\u{fc}\u{f1}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{e9}\u{fc}\u{f1}   | Charlie |\n| Delta | \u{e9}\u{fc}\u{f1}     |",
    },
    Vector {
        id: "unicode.accented-precomposed/3153",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{e9}\u{fc}\u{f1}\u{e9}\u{fc}\u{f1}\u{e9}\u{fc}\u{f1}"]],
        expected: "| ascii | \u{e9}\u{fc}\u{f1}\u{e9}\u{fc}\u{f1}\u{e9}\u{fc}\u{f1} |\n| ----- | --------- |",
    },
    Vector {
        id: "unicode.astral-cjk-ext/3033",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{2000b}\u{2000c}\u{2000d}", "Charlie"], &["Delta", "\u{2000b}\u{2000c}\u{2000d}"]],
        expected: "| Alpha  | Bravo   |\n| ------ | ------- |\n| \u{2000b}\u{2000c}\u{2000d} | Charlie |\n| Delta  | \u{2000b}\u{2000c}\u{2000d}  |",
    },
    Vector {
        id: "unicode.astral-cjk-ext/3057",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{2000b}\u{2000c}\u{2000d}\u{2000b}\u{2000c}\u{2000d}\u{2000b}\u{2000c}\u{2000d}"]],
        expected: "| ascii | \u{2000b}\u{2000c}\u{2000d}\u{2000b}\u{2000c}\u{2000d}\u{2000b}\u{2000c}\u{2000d} |\n| ----- | ------------------ |",
    },
    Vector {
        id: "unicode.astral-plane/2985",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{1d518}\u{1d52b}\u{1d526}\u{1d520}\u{1d52c}\u{1d521}\u{1d522}", "Charlie"], &["Delta", "\u{1d518}\u{1d52b}\u{1d526}\u{1d520}\u{1d52c}\u{1d521}\u{1d522}"]],
        expected: "| Alpha          | Bravo          |\n| -------------- | -------------- |\n| \u{1d518}\u{1d52b}\u{1d526}\u{1d520}\u{1d52c}\u{1d521}\u{1d522} | Charlie        |\n| Delta          | \u{1d518}\u{1d52b}\u{1d526}\u{1d520}\u{1d52c}\u{1d521}\u{1d522} |",
    },
    Vector {
        id: "unicode.astral-plane/3009",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{1d518}\u{1d52b}\u{1d526}\u{1d520}\u{1d52c}\u{1d521}\u{1d522}\u{1d518}\u{1d52b}\u{1d526}\u{1d520}\u{1d52c}\u{1d521}\u{1d522}\u{1d518}\u{1d52b}\u{1d526}\u{1d520}\u{1d52c}\u{1d521}\u{1d522}"]],
        expected: "| ascii | \u{1d518}\u{1d52b}\u{1d526}\u{1d520}\u{1d52c}\u{1d521}\u{1d522}\u{1d518}\u{1d52b}\u{1d526}\u{1d520}\u{1d52c}\u{1d521}\u{1d522}\u{1d518}\u{1d52b}\u{1d526}\u{1d520}\u{1d52c}\u{1d521}\u{1d522} |\n| ----- | ------------------------------------------ |",
    },
    Vector {
        id: "unicode.bidi-isolate/2937",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{2066}abc\u{2069}", "Charlie"], &["Delta", "\u{2066}abc\u{2069}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{2066}abc\u{2069} | Charlie |\n| Delta | \u{2066}abc\u{2069}   |",
    },
    Vector {
        id: "unicode.bidi-isolate/2961",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{2066}abc\u{2069}\u{2066}abc\u{2069}\u{2066}abc\u{2069}"]],
        expected: "| ascii | \u{2066}abc\u{2069}\u{2066}abc\u{2069}\u{2066}abc\u{2069} |\n| ----- | --------------- |",
    },
    Vector {
        id: "unicode.bom/2697",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{feff}abc", "Charlie"], &["Delta", "\u{feff}abc"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{feff}abc  | Charlie |\n| Delta | \u{feff}abc    |",
    },
    Vector {
        id: "unicode.bom/2721",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{feff}abc\u{feff}abc\u{feff}abc"]],
        expected: "| ascii | \u{feff}abc\u{feff}abc\u{feff}abc |\n| ----- | ------------ |",
    },
    Vector {
        id: "unicode.cjk-long/1881",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{6f22}\u{5b57}\u{4eee}\u{540d}\u{4ea4}\u{3058}\u{308a}\u{6587}", "Charlie"], &["Delta", "\u{6f22}\u{5b57}\u{4eee}\u{540d}\u{4ea4}\u{3058}\u{308a}\u{6587}"]],
        expected: "| Alpha    | Bravo    |\n| -------- | -------- |\n| \u{6f22}\u{5b57}\u{4eee}\u{540d}\u{4ea4}\u{3058}\u{308a}\u{6587} | Charlie  |\n| Delta    | \u{6f22}\u{5b57}\u{4eee}\u{540d}\u{4ea4}\u{3058}\u{308a}\u{6587} |",
    },
    Vector {
        id: "unicode.cjk-long/1905",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{6f22}\u{5b57}\u{4eee}\u{540d}\u{4ea4}\u{3058}\u{308a}\u{6587}\u{6f22}\u{5b57}\u{4eee}\u{540d}\u{4ea4}\u{3058}\u{308a}\u{6587}\u{6f22}\u{5b57}\u{4eee}\u{540d}\u{4ea4}\u{3058}\u{308a}\u{6587}"]],
        expected: "| ascii | \u{6f22}\u{5b57}\u{4eee}\u{540d}\u{4ea4}\u{3058}\u{308a}\u{6587}\u{6f22}\u{5b57}\u{4eee}\u{540d}\u{4ea4}\u{3058}\u{308a}\u{6587}\u{6f22}\u{5b57}\u{4eee}\u{540d}\u{4ea4}\u{3058}\u{308a}\u{6587} |\n| ----- | ------------------------ |",
    },
    Vector {
        id: "unicode.cjk-wide/1833",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{4e2d}\u{6587}", "Charlie"], &["Delta", "\u{4e2d}\u{6587}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{4e2d}\u{6587}    | Charlie |\n| Delta | \u{4e2d}\u{6587}      |",
    },
    Vector {
        id: "unicode.cjk-wide/1857",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{4e2d}\u{6587}\u{4e2d}\u{6587}\u{4e2d}\u{6587}"]],
        expected: "| ascii | \u{4e2d}\u{6587}\u{4e2d}\u{6587}\u{4e2d}\u{6587} |\n| ----- | ------ |",
    },
    Vector {
        id: "unicode.combining-acute/1689",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["e\u{301}", "Charlie"], &["Delta", "e\u{301}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| e\u{301}    | Charlie |\n| Delta | e\u{301}      |",
    },
    Vector {
        id: "unicode.combining-acute/1713",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "e\u{301}e\u{301}e\u{301}"]],
        expected: "| ascii | e\u{301}e\u{301}e\u{301} |\n| ----- | ------ |",
    },
    Vector {
        id: "unicode.combining-only/1785",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{301}", "Charlie"], &["Delta", "\u{301}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{301}     | Charlie |\n| Delta | \u{301}       |",
    },
    Vector {
        id: "unicode.combining-only/1809",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{301}\u{301}\u{301}"]],
        expected: "| ascii | \u{301}\u{301}\u{301} |\n| ----- | --- |",
    },
    Vector {
        id: "unicode.combining-stack/1737",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["a\u{301}\u{302}\u{303}\u{304}", "Charlie"], &["Delta", "a\u{301}\u{302}\u{303}\u{304}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| a\u{301}\u{302}\u{303}\u{304} | Charlie |\n| Delta | a\u{301}\u{302}\u{303}\u{304}   |",
    },
    Vector {
        id: "unicode.combining-stack/1761",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "a\u{301}\u{302}\u{303}\u{304}a\u{301}\u{302}\u{303}\u{304}a\u{301}\u{302}\u{303}\u{304}"]],
        expected: "| ascii | a\u{301}\u{302}\u{303}\u{304}a\u{301}\u{302}\u{303}\u{304}a\u{301}\u{302}\u{303}\u{304} |\n| ----- | --------------- |",
    },
    Vector {
        id: "unicode.devanagari-cluster/3273",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{915}\u{94d}\u{937}", "Charlie"], &["Delta", "\u{915}\u{94d}\u{937}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{915}\u{94d}\u{937}   | Charlie |\n| Delta | \u{915}\u{94d}\u{937}     |",
    },
    Vector {
        id: "unicode.devanagari-cluster/3297",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{915}\u{94d}\u{937}\u{915}\u{94d}\u{937}\u{915}\u{94d}\u{937}"]],
        expected: "| ascii | \u{915}\u{94d}\u{937}\u{915}\u{94d}\u{937}\u{915}\u{94d}\u{937} |\n| ----- | --------- |",
    },
    Vector {
        id: "unicode.emoji-flag/2313",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{1f1fa}\u{1f1f8}", "Charlie"], &["Delta", "\u{1f1fa}\u{1f1f8}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{1f1fa}\u{1f1f8}  | Charlie |\n| Delta | \u{1f1fa}\u{1f1f8}    |",
    },
    Vector {
        id: "unicode.emoji-flag/2337",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{1f1fa}\u{1f1f8}\u{1f1fa}\u{1f1f8}\u{1f1fa}\u{1f1f8}"]],
        expected: "| ascii | \u{1f1fa}\u{1f1f8}\u{1f1fa}\u{1f1f8}\u{1f1fa}\u{1f1f8} |\n| ----- | ------------ |",
    },
    Vector {
        id: "unicode.emoji-keycap/2361",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["1\u{fe0f}\u{20e3}", "Charlie"], &["Delta", "1\u{fe0f}\u{20e3}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| 1\u{fe0f}\u{20e3}   | Charlie |\n| Delta | 1\u{fe0f}\u{20e3}     |",
    },
    Vector {
        id: "unicode.emoji-keycap/2385",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "1\u{fe0f}\u{20e3}1\u{fe0f}\u{20e3}1\u{fe0f}\u{20e3}"]],
        expected: "| ascii | 1\u{fe0f}\u{20e3}1\u{fe0f}\u{20e3}1\u{fe0f}\u{20e3} |\n| ----- | --------- |",
    },
    Vector {
        id: "unicode.emoji-skin-tone/2169",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{1f44d}\u{1f3fd}", "Charlie"], &["Delta", "\u{1f44d}\u{1f3fd}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{1f44d}\u{1f3fd}  | Charlie |\n| Delta | \u{1f44d}\u{1f3fd}    |",
    },
    Vector {
        id: "unicode.emoji-skin-tone/2193",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{1f44d}\u{1f3fd}\u{1f44d}\u{1f3fd}\u{1f44d}\u{1f3fd}"]],
        expected: "| ascii | \u{1f44d}\u{1f3fd}\u{1f44d}\u{1f3fd}\u{1f44d}\u{1f3fd} |\n| ----- | ------------ |",
    },
    Vector {
        id: "unicode.emoji-zwj-couple/2265",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{1f469}\u{200d}\u{2764}\u{fe0f}\u{200d}\u{1f469}", "Charlie"], &["Delta", "\u{1f469}\u{200d}\u{2764}\u{fe0f}\u{200d}\u{1f469}"]],
        expected: "| Alpha    | Bravo    |\n| -------- | -------- |\n| \u{1f469}\u{200d}\u{2764}\u{fe0f}\u{200d}\u{1f469} | Charlie  |\n| Delta    | \u{1f469}\u{200d}\u{2764}\u{fe0f}\u{200d}\u{1f469} |",
    },
    Vector {
        id: "unicode.emoji-zwj-couple/2289",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{1f469}\u{200d}\u{2764}\u{fe0f}\u{200d}\u{1f469}\u{1f469}\u{200d}\u{2764}\u{fe0f}\u{200d}\u{1f469}\u{1f469}\u{200d}\u{2764}\u{fe0f}\u{200d}\u{1f469}"]],
        expected: "| ascii | \u{1f469}\u{200d}\u{2764}\u{fe0f}\u{200d}\u{1f469}\u{1f469}\u{200d}\u{2764}\u{fe0f}\u{200d}\u{1f469}\u{1f469}\u{200d}\u{2764}\u{fe0f}\u{200d}\u{1f469} |\n| ----- | ------------------------ |",
    },
    Vector {
        id: "unicode.emoji-zwj-family/2217",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{1f468}\u{200d}\u{1f469}\u{200d}\u{1f467}\u{200d}\u{1f466}", "Charlie"], &["Delta", "\u{1f468}\u{200d}\u{1f469}\u{200d}\u{1f467}\u{200d}\u{1f466}"]],
        expected: "| Alpha       | Bravo       |\n| ----------- | ----------- |\n| \u{1f468}\u{200d}\u{1f469}\u{200d}\u{1f467}\u{200d}\u{1f466} | Charlie     |\n| Delta       | \u{1f468}\u{200d}\u{1f469}\u{200d}\u{1f467}\u{200d}\u{1f466} |",
    },
    Vector {
        id: "unicode.emoji-zwj-family/2241",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{1f468}\u{200d}\u{1f469}\u{200d}\u{1f467}\u{200d}\u{1f466}\u{1f468}\u{200d}\u{1f469}\u{200d}\u{1f467}\u{200d}\u{1f466}\u{1f468}\u{200d}\u{1f469}\u{200d}\u{1f467}\u{200d}\u{1f466}"]],
        expected: "| ascii | \u{1f468}\u{200d}\u{1f469}\u{200d}\u{1f467}\u{200d}\u{1f466}\u{1f468}\u{200d}\u{1f469}\u{200d}\u{1f467}\u{200d}\u{1f466}\u{1f468}\u{200d}\u{1f469}\u{200d}\u{1f467}\u{200d}\u{1f466} |\n| ----- | --------------------------------- |",
    },
    Vector {
        id: "unicode.emoji/2121",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{1f600}", "Charlie"], &["Delta", "\u{1f600}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{1f600}    | Charlie |\n| Delta | \u{1f600}      |",
    },
    Vector {
        id: "unicode.emoji/2145",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{1f600}\u{1f600}\u{1f600}"]],
        expected: "| ascii | \u{1f600}\u{1f600}\u{1f600} |\n| ----- | ------ |",
    },
    Vector {
        id: "unicode.enclosing-keycap-raw/3321",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{20e3}", "Charlie"], &["Delta", "\u{20e3}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{20e3}     | Charlie |\n| Delta | \u{20e3}       |",
    },
    Vector {
        id: "unicode.enclosing-keycap-raw/3345",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{20e3}\u{20e3}\u{20e3}"]],
        expected: "| ascii | \u{20e3}\u{20e3}\u{20e3} |\n| ----- | --- |",
    },
    Vector {
        id: "unicode.fullwidth-latin/2025",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{ff21}\u{ff22}\u{ff23}", "Charlie"], &["Delta", "\u{ff21}\u{ff22}\u{ff23}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{ff21}\u{ff22}\u{ff23}   | Charlie |\n| Delta | \u{ff21}\u{ff22}\u{ff23}     |",
    },
    Vector {
        id: "unicode.fullwidth-latin/2049",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{ff21}\u{ff22}\u{ff23}\u{ff21}\u{ff22}\u{ff23}\u{ff21}\u{ff22}\u{ff23}"]],
        expected: "| ascii | \u{ff21}\u{ff22}\u{ff23}\u{ff21}\u{ff22}\u{ff23}\u{ff21}\u{ff22}\u{ff23} |\n| ----- | --------- |",
    },
    Vector {
        id: "unicode.halfwidth_kana/2073",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{ff71}\u{ff72}\u{ff73}", "Charlie"], &["Delta", "\u{ff71}\u{ff72}\u{ff73}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{ff71}\u{ff72}\u{ff73}   | Charlie |\n| Delta | \u{ff71}\u{ff72}\u{ff73}     |",
    },
    Vector {
        id: "unicode.halfwidth_kana/2097",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{ff71}\u{ff72}\u{ff73}\u{ff71}\u{ff72}\u{ff73}\u{ff71}\u{ff72}\u{ff73}"]],
        expected: "| ascii | \u{ff71}\u{ff72}\u{ff73}\u{ff71}\u{ff72}\u{ff73}\u{ff71}\u{ff72}\u{ff73} |\n| ----- | --------- |",
    },
    Vector {
        id: "unicode.hangul-jamo/1977",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{1100}\u{1161}\u{11a8}", "Charlie"], &["Delta", "\u{1100}\u{1161}\u{11a8}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{1100}\u{1161}\u{11a8}   | Charlie |\n| Delta | \u{1100}\u{1161}\u{11a8}     |",
    },
    Vector {
        id: "unicode.hangul-jamo/2001",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{1100}\u{1161}\u{11a8}\u{1100}\u{1161}\u{11a8}\u{1100}\u{1161}\u{11a8}"]],
        expected: "| ascii | \u{1100}\u{1161}\u{11a8}\u{1100}\u{1161}\u{11a8}\u{1100}\u{1161}\u{11a8} |\n| ----- | --------- |",
    },
    Vector {
        id: "unicode.hangul/1929",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{d55c}\u{ad6d}\u{c5b4}", "Charlie"], &["Delta", "\u{d55c}\u{ad6d}\u{c5b4}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{d55c}\u{ad6d}\u{c5b4}   | Charlie |\n| Delta | \u{d55c}\u{ad6d}\u{c5b4}     |",
    },
    Vector {
        id: "unicode.hangul/1953",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{d55c}\u{ad6d}\u{c5b4}\u{d55c}\u{ad6d}\u{c5b4}\u{d55c}\u{ad6d}\u{c5b4}"]],
        expected: "| ascii | \u{d55c}\u{ad6d}\u{c5b4}\u{d55c}\u{ad6d}\u{c5b4}\u{d55c}\u{ad6d}\u{c5b4} |\n| ----- | --------- |",
    },
    Vector {
        id: "unicode.noncharacter/3465",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{fdd0}", "Charlie"], &["Delta", "\u{fdd0}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{fdd0}     | Charlie |\n| Delta | \u{fdd0}       |",
    },
    Vector {
        id: "unicode.noncharacter/3489",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{fdd0}\u{fdd0}\u{fdd0}"]],
        expected: "| ascii | \u{fdd0}\u{fdd0}\u{fdd0} |\n| ----- | --- |",
    },
    Vector {
        id: "unicode.private-use/3369",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{e000}", "Charlie"], &["Delta", "\u{e000}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{e000}     | Charlie |\n| Delta | \u{e000}       |",
    },
    Vector {
        id: "unicode.private-use/3393",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{e000}\u{e000}\u{e000}"]],
        expected: "| ascii | \u{e000}\u{e000}\u{e000} |\n| ----- | --- |",
    },
    Vector {
        id: "unicode.replacement-char/3417",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{fffd}", "Charlie"], &["Delta", "\u{fffd}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{fffd}     | Charlie |\n| Delta | \u{fffd}       |",
    },
    Vector {
        id: "unicode.replacement-char/3441",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{fffd}\u{fffd}\u{fffd}"]],
        expected: "| ascii | \u{fffd}\u{fffd}\u{fffd} |\n| ----- | --- |",
    },
    Vector {
        id: "unicode.rtl-marks/2889",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{202e}abc\u{202c}", "Charlie"], &["Delta", "\u{202e}abc\u{202c}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{202e}abc\u{202c} | Charlie |\n| Delta | \u{202e}abc\u{202c}   |",
    },
    Vector {
        id: "unicode.rtl-marks/2913",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{202e}abc\u{202c}\u{202e}abc\u{202c}\u{202e}abc\u{202c}"]],
        expected: "| ascii | \u{202e}abc\u{202c}\u{202e}abc\u{202c}\u{202e}abc\u{202c} |\n| ----- | --------------- |",
    },
    Vector {
        id: "unicode.rtl-mixed/2841",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["abc \u{5e9}\u{5dc}\u{5d5}\u{5dd} def", "Charlie"], &["Delta", "abc \u{5e9}\u{5dc}\u{5d5}\u{5dd} def"]],
        expected: "| Alpha        | Bravo        |\n| ------------ | ------------ |\n| abc \u{5e9}\u{5dc}\u{5d5}\u{5dd} def | Charlie      |\n| Delta        | abc \u{5e9}\u{5dc}\u{5d5}\u{5dd} def |",
    },
    Vector {
        id: "unicode.rtl-mixed/2865",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "abc \u{5e9}\u{5dc}\u{5d5}\u{5dd} defabc \u{5e9}\u{5dc}\u{5d5}\u{5dd} defabc \u{5e9}\u{5dc}\u{5d5}\u{5dd} def"]],
        expected: "| ascii | abc \u{5e9}\u{5dc}\u{5d5}\u{5dd} defabc \u{5e9}\u{5dc}\u{5d5}\u{5dd} defabc \u{5e9}\u{5dc}\u{5d5}\u{5dd} def |\n| ----- | ------------------------------------ |",
    },
    Vector {
        id: "unicode.rtl_arabic/2793",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{645}\u{631}\u{62d}\u{628}\u{627}", "Charlie"], &["Delta", "\u{645}\u{631}\u{62d}\u{628}\u{627}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{645}\u{631}\u{62d}\u{628}\u{627} | Charlie |\n| Delta | \u{645}\u{631}\u{62d}\u{628}\u{627}   |",
    },
    Vector {
        id: "unicode.rtl_arabic/2817",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{645}\u{631}\u{62d}\u{628}\u{627}\u{645}\u{631}\u{62d}\u{628}\u{627}\u{645}\u{631}\u{62d}\u{628}\u{627}"]],
        expected: "| ascii | \u{645}\u{631}\u{62d}\u{628}\u{627}\u{645}\u{631}\u{62d}\u{628}\u{627}\u{645}\u{631}\u{62d}\u{628}\u{627} |\n| ----- | --------------- |",
    },
    Vector {
        id: "unicode.rtl_hebrew/2745",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{5e9}\u{5dc}\u{5d5}\u{5dd}", "Charlie"], &["Delta", "\u{5e9}\u{5dc}\u{5d5}\u{5dd}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{5e9}\u{5dc}\u{5d5}\u{5dd}  | Charlie |\n| Delta | \u{5e9}\u{5dc}\u{5d5}\u{5dd}    |",
    },
    Vector {
        id: "unicode.rtl_hebrew/2769",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{5e9}\u{5dc}\u{5d5}\u{5dd}\u{5e9}\u{5dc}\u{5d5}\u{5dd}\u{5e9}\u{5dc}\u{5d5}\u{5dd}"]],
        expected: "| ascii | \u{5e9}\u{5dc}\u{5d5}\u{5dd}\u{5e9}\u{5dc}\u{5d5}\u{5dd}\u{5e9}\u{5dc}\u{5d5}\u{5dd} |\n| ----- | ------------ |",
    },
    Vector {
        id: "unicode.soft-hyphen/2649",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["a\u{ad}b", "Charlie"], &["Delta", "a\u{ad}b"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| a\u{ad}b   | Charlie |\n| Delta | a\u{ad}b     |",
    },
    Vector {
        id: "unicode.soft-hyphen/2673",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "a\u{ad}ba\u{ad}ba\u{ad}b"]],
        expected: "| ascii | a\u{ad}ba\u{ad}ba\u{ad}b |\n| ----- | --------- |",
    },
    Vector {
        id: "unicode.surrogate-pair-adjacent/3081",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{1f600}\u{1f600}\u{1f600}", "Charlie"], &["Delta", "\u{1f600}\u{1f600}\u{1f600}"]],
        expected: "| Alpha  | Bravo   |\n| ------ | ------- |\n| \u{1f600}\u{1f600}\u{1f600} | Charlie |\n| Delta  | \u{1f600}\u{1f600}\u{1f600}  |",
    },
    Vector {
        id: "unicode.surrogate-pair-adjacent/3105",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{1f600}\u{1f600}\u{1f600}\u{1f600}\u{1f600}\u{1f600}\u{1f600}\u{1f600}\u{1f600}"]],
        expected: "| ascii | \u{1f600}\u{1f600}\u{1f600}\u{1f600}\u{1f600}\u{1f600}\u{1f600}\u{1f600}\u{1f600} |\n| ----- | ------------------ |",
    },
    Vector {
        id: "unicode.tag-characters/3513",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["a\u{e0061}b", "Charlie"], &["Delta", "a\u{e0061}b"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| a\u{e0061}b  | Charlie |\n| Delta | a\u{e0061}b    |",
    },
    Vector {
        id: "unicode.tag-characters/3537",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "a\u{e0061}ba\u{e0061}ba\u{e0061}b"]],
        expected: "| ascii | a\u{e0061}ba\u{e0061}ba\u{e0061}b |\n| ----- | ------------ |",
    },
    Vector {
        id: "unicode.thai-combining/3225",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{e01}\u{e34}\u{e49}", "Charlie"], &["Delta", "\u{e01}\u{e34}\u{e49}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{e01}\u{e34}\u{e49}   | Charlie |\n| Delta | \u{e01}\u{e34}\u{e49}     |",
    },
    Vector {
        id: "unicode.thai-combining/3249",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{e01}\u{e34}\u{e49}\u{e01}\u{e34}\u{e49}\u{e01}\u{e34}\u{e49}"]],
        expected: "| ascii | \u{e01}\u{e34}\u{e49}\u{e01}\u{e34}\u{e49}\u{e01}\u{e34}\u{e49} |\n| ----- | --------- |",
    },
    Vector {
        id: "unicode.variation-selector/2409",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["\u{2764}\u{fe0f}", "Charlie"], &["Delta", "\u{2764}\u{fe0f}"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| \u{2764}\u{fe0f}    | Charlie |\n| Delta | \u{2764}\u{fe0f}      |",
    },
    Vector {
        id: "unicode.variation-selector/2433",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "\u{2764}\u{fe0f}\u{2764}\u{fe0f}\u{2764}\u{fe0f}"]],
        expected: "| ascii | \u{2764}\u{fe0f}\u{2764}\u{fe0f}\u{2764}\u{fe0f} |\n| ----- | ------ |",
    },
    Vector {
        id: "unicode.word-joiner/2601",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["a\u{2060}b", "Charlie"], &["Delta", "a\u{2060}b"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| a\u{2060}b   | Charlie |\n| Delta | a\u{2060}b     |",
    },
    Vector {
        id: "unicode.word-joiner/2625",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "a\u{2060}ba\u{2060}ba\u{2060}b"]],
        expected: "| ascii | a\u{2060}ba\u{2060}ba\u{2060}b |\n| ----- | --------- |",
    },
    Vector {
        id: "unicode.zero-width-joiner/2457",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["a\u{200d}b", "Charlie"], &["Delta", "a\u{200d}b"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| a\u{200d}b   | Charlie |\n| Delta | a\u{200d}b     |",
    },
    Vector {
        id: "unicode.zero-width-joiner/2481",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "a\u{200d}ba\u{200d}ba\u{200d}b"]],
        expected: "| ascii | a\u{200d}ba\u{200d}ba\u{200d}b |\n| ----- | --------- |",
    },
    Vector {
        id: "unicode.zero-width-nonjoiner/2553",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["a\u{200c}b", "Charlie"], &["Delta", "a\u{200c}b"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| a\u{200c}b   | Charlie |\n| Delta | a\u{200c}b     |",
    },
    Vector {
        id: "unicode.zero-width-nonjoiner/2577",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "a\u{200c}ba\u{200c}ba\u{200c}b"]],
        expected: "| ascii | a\u{200c}ba\u{200c}ba\u{200c}b |\n| ----- | --------- |",
    },
    Vector {
        id: "unicode.zero-width-space/2505",
        utf16: true,
        alignments: &[],
        rows: &[&["Alpha", "Bravo"], &["a\u{200b}b", "Charlie"], &["Delta", "a\u{200b}b"]],
        expected: "| Alpha | Bravo   |\n| ----- | ------- |\n| a\u{200b}b   | Charlie |\n| Delta | a\u{200b}b     |",
    },
    Vector {
        id: "unicode.zero-width-space/2529",
        utf16: true,
        alignments: &[],
        rows: &[&["ascii", "a\u{200b}ba\u{200b}ba\u{200b}b"]],
        expected: "| ascii | a\u{200b}ba\u{200b}ba\u{200b}b |\n| ----- | --------- |",
    },
];
